apiVersion: v1
kind: Secret
metadata:
  name: climbup-secrets
  namespace: climbup-prod
type: Opaque
stringData:
  # Database credentials
  postgres-password: "REPLACE_WITH_ACTUAL_PASSWORD"
  mongodb-password: "REPLACE_WITH_ACTUAL_PASSWORD"
  
  # JWT secrets
  jwt-secret-key: "REPLACE_WITH_ACTUAL_SECRET"
  
  # Redis password if using authentication
  redis-password: "REPLACE_WITH_ACTUAL_PASSWORD"
  
  # API keys and other secrets
  payment-gateway-key: "REPLACE_WITH_ACTUAL_KEY"
  email-service-key: "REPLACE_WITH_ACTUAL_KEY" 